import 'keys.dart';

Map<String, String> ar = {
  appName: 'lomfu',
  lblTeacher: 'المعلم',
  lblStudent: 'الطالب',
  lblWelcome: 'مرحبا بك في',
  lblHome: 'الرئيسية',
  lblLogin: 'تسجيل الدخول',
  lblRegister: 'تسجيل حساب',
  lblLogout: 'تسجيل الخروج',
  lblForgotPassword: 'نسيت كلمة المرور',
  lblOrLoginWith: 'أو تسجيل الدخول بواسطة',
  lblDontHaveAccount: 'ليس لديك حساب؟',
  lblAlreadyHaveAccount: 'لديك حساب بالفعل؟',
  lblProfile: 'الملف الشخصي',
  lblSubjects: 'المواد',
  lblCourses: 'الدورات',
  lblMyCourses: 'دوراتي',
  lblArabicLang: 'العربية',
  lblEnglishLang: 'الإنجليزية',
  lblEnterYourDetails: 'أدخل تفاصيلك أدناه لإنشاء حسابك',
  lblPolicyPrivacy: 'بإنشاء حساب، فإنك توافق على شروطنا وأحكامنا.',
  lblVerifyEmail: 'تحقق من البريد الإلكتروني',
  lblCodeSentTo: 'تم إرسال الرمز إلى',
  lblDontRecieveCode: 'لم تستلم الرمز؟',
  lblResendCode: 'إعادة إرسال',
  lblResetPassword: 'إعادة تعيين كلمة المرور',
  lblNoSubjects: 'لا توجد مواد',
  lblNoCourses: 'لا توجد دورات',
  lblLearning: 'التعلم',
  lblNewCourse: 'دورة جديدة',
  lblEditCourse: 'تعديل الدورة',
  lblchooseCoursePhoto: 'اختر صورة الدورة',
  lblEditPhoto: 'تعديل الصورة',
  lblNoPhotoAvailable: 'لا تتوفر صورة',
  lblNoPhotoSelected: 'لم يتم اختيار صورة',
  lblDeleteCourse: 'حذف الدورة',
  lblAreYouSureYouWantToDeleteThisCourse:
      'هل أنت متأكد أنك تريد حذف هذه الدورة؟',
  lblError: 'خطأ',

  // hnt
  hntEmail: 'البريد الإلكتروني',
  hntPassword: 'كلمة المرور',
  hntConfirmPassword: 'تأكيد كلمة المرور',
  hntName: 'الاسم',
  hntRole: 'الدور',
  hntPhone: 'الهاتف',
  hntSelectSubject: 'اختر موضوع',
  hntPleaseSelectASubject: 'الرجاء اختيار موضوع',

  // btn
  btnNext: 'التالي',
  btnSkip: 'تخطي',
  btnLogin: 'تسجيل الدخول',
  btnRegister: 'تسجيل حساب',
  btnLogout: 'تسجيل الخروج',
  btnForgotPassword: 'نسيت كلمة المرور',
  btnSend: 'إرسال',
  btnSubmit: 'تقديم',
  btnVerify: 'تحقق',
  btnCancel: 'إلغاء',
  btnDelete: 'حذف',
  btnAdd: 'إضافة',
  btnUpdate: 'تحديث',
  btnYes: 'نعم',
  btnNo: 'لا',
};
