
import 'keys.dart';

Map<String, String> en = {
  appName: 'lomfu',
  lblTeacher: 'Teacher',
  lblStudent: 'Student',
  lblWelcome: 'Welcome to ',
  lblHome: 'Home',
  lblLogin: 'Login',
  lblRegister: 'Register',
  lblLogout: 'Logout',
  lblForgotPassword: 'Forgot Password',
  lblOrLoginWith: 'Or login with',
  lblDontHaveAccount: 'Don\'t have an account?',
  lblAlreadyHaveAccount: 'Already have an account?',
  lblProfile: 'Profile',
  lblSubjects: 'Subjects',
  lblCourses: 'Courses',
  lblMyCourses: 'My Courses',
  lblArabicLang: 'Arabic',
  lblEnglishLang: 'English',
  lblEnterYourDetails: 'Enter your details below to create your account',
  lblPolicyPrivacy: 'By creating an account, you agree to our Terms & Conditions.',
  lblVerifyEmail: 'Verify Email',
  lblCodeSentTo: 'Code is sent to',
  lblDontRecieveCode: 'Didn\'t receive the code?',
  lblResendCode: 'Resend Code',
  lblResetPassword: 'Reset Password',
  lblNoSubjects: 'No Subjects',
  lblNoCourses: 'No Courses',
  lblLearning: 'Learning',  

  hntEmail: 'Email',
  hntPassword: 'Password',
  hntConfirmPassword: 'Confirm Password',
  hntName: 'Name',
  hntRole: 'Role',
  hntPhone: 'Phone',
  
  btnNext: 'Next',
  btnSkip: 'Skip',
  btnLogin: 'Login',
  btnRegister: 'Register',
  btnLogout: 'Logout',
  btnForgotPassword: 'Forgot Password',
  btnSend: 'Send',
  btnSubmit: 'Submit',
  btnVerify: 'Verify',
};